/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VerificationDialog.java
 *
 * Created on Sep 27, 2011, 3:47:55 PM
 */

package org.fhwa.c2cri.gui;

/**
 * The Class VerificationDialog.
 *
 * @author TransCore ITS, LLC
 */
public class VerificationDialog extends javax.swing.JDialog {

    /** The passed. */
    private boolean passed = false;
    
    /** The skip remaining user verifications. */
    private boolean skipRemainingUserVerifications = false;

    /**
     * Creates new form VerificationDialog.
     *
     * @param parent the parent
     * @param modal the modal
     */
    public VerificationDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MessagePanel = new javax.swing.JPanel();
        messageTabbedPane = new javax.swing.JTabbedPane();
        messageSpecificationScrollPane = new javax.swing.JScrollPane();
        messageSpecificationTextArea = new javax.swing.JTextArea();
        rawMessageScrollPane = new javax.swing.JScrollPane();
        rawMessageTextArea = new javax.swing.JTextArea();
        ButtonPanel = new javax.swing.JPanel();
        passButton = new javax.swing.JButton();
        failButton = new javax.swing.JButton();
        skipCheckBox = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        VerificationContextPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        verificationContextTextArea = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("User Message Content Verification");
        setMinimumSize(new java.awt.Dimension(425, 325));

        MessagePanel.setMinimumSize(new java.awt.Dimension(150, 200));

        messageTabbedPane.setMinimumSize(new java.awt.Dimension(0, 0));
        messageTabbedPane.setName("MessageSpecification"); // NOI18N

        messageSpecificationTextArea.setColumns(20);
        messageSpecificationTextArea.setEditable(false);
        messageSpecificationTextArea.setRows(5);
        messageSpecificationScrollPane.setViewportView(messageSpecificationTextArea);

        messageTabbedPane.addTab("Message Specification", messageSpecificationScrollPane);

        rawMessageTextArea.setColumns(20);
        rawMessageTextArea.setEditable(false);
        rawMessageTextArea.setRows(5);
        rawMessageScrollPane.setViewportView(rawMessageTextArea);

        messageTabbedPane.addTab("Raw Message", rawMessageScrollPane);

        passButton.setText("Pass");
        passButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passButtonActionPerformed(evt);
            }
        });

        failButton.setText("Fail");
        failButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                failButtonActionPerformed(evt);
            }
        });

        skipCheckBox.setText("Skip remaining user verification steps");

        jLabel1.setText("Click the button matching the results of the user's verification.");

        javax.swing.GroupLayout ButtonPanelLayout = new javax.swing.GroupLayout(ButtonPanel);
        ButtonPanel.setLayout(ButtonPanelLayout);
        ButtonPanelLayout.setHorizontalGroup(
            ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonPanelLayout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addGroup(ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(skipCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ButtonPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(passButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                        .addComponent(failButton)))
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(ButtonPanelLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        ButtonPanelLayout.setVerticalGroup(
            ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonPanelLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passButton)
                    .addComponent(failButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(skipCheckBox)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        verificationContextTextArea.setColumns(20);
        verificationContextTextArea.setEditable(false);
        verificationContextTextArea.setRows(5);
        jScrollPane1.setViewportView(verificationContextTextArea);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Verification Statement");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap(117, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout VerificationContextPanelLayout = new javax.swing.GroupLayout(VerificationContextPanel);
        VerificationContextPanel.setLayout(VerificationContextPanelLayout);
        VerificationContextPanelLayout.setHorizontalGroup(
            VerificationContextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VerificationContextPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
        );
        VerificationContextPanelLayout.setVerticalGroup(
            VerificationContextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VerificationContextPanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MessagePanelLayout = new javax.swing.GroupLayout(MessagePanel);
        MessagePanel.setLayout(MessagePanelLayout);
        MessagePanelLayout.setHorizontalGroup(
            MessagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MessagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MessagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ButtonPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(messageTabbedPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                    .addComponent(VerificationContextPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        MessagePanelLayout.setVerticalGroup(
            MessagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MessagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(VerificationContextPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(messageTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                .addGap(17, 17, 17)
                .addComponent(ButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MessagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MessagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Pass button action performed.
     * 
     * Pre-Conditions: N/A
     * Post-Conditions: N/A
     *
     * @param evt the evt
     */
    private void passButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passButtonActionPerformed
        passed = true;
        skipRemainingUserVerifications = skipCheckBox.isSelected();
        this.setVisible(false);
    }//GEN-LAST:event_passButtonActionPerformed

    /**
     * Fail button action performed.
     * 
     * Pre-Conditions: N/A
     * Post-Conditions: N/A
     *
     * @param evt the evt
     */
    private void failButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_failButtonActionPerformed
        passed = false;
        skipRemainingUserVerifications = skipCheckBox.isSelected();
        this.setVisible(false);
    }//GEN-LAST:event_failButtonActionPerformed

    /**
     * Checks if is passed.
     * 
     * Pre-Conditions: N/A
     * Post-Conditions: N/A
     *
     * @return true, if is passed
     */
    public boolean isPassed() {
        return passed;
    }

    /**
     * Checks if is skip remaining user verifications.
     * 
     * Pre-Conditions: N/A
     * Post-Conditions: N/A
     *
     * @return true, if is skip remaining user verifications
     */
    public boolean isSkipRemainingUserVerifications() {
        return skipRemainingUserVerifications;
    }

    /**
     * Sets the message specification.
     *
     * @param specification the new message specification
     */
    public void setMessageSpecification(String specification){
        this.messageSpecificationTextArea.setText(specification);
        this.messageSpecificationTextArea.setCaretPosition(0);
    }

    /**
     * Sets the raw message.
     *
     * @param rawMessage the new raw message
     */
    public void setRawMessage(String rawMessage){
        this.rawMessageTextArea.setText(rawMessage);
        this.rawMessageTextArea.setCaretPosition(0);
    }

    /**
     * Sets the verification instruction.
     *
     * @param instruction the new verification instruction
     */
    public void setVerificationInstruction(String instruction){
        this.verificationContextTextArea.setText(instruction);
        this.verificationContextTextArea.setCaretPosition(0);
    }
    
    /**
     * The main method.
     * 
     * Pre-Conditions: N/A
     * Post-Conditions: N/A
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VerificationDialog dialog = new VerificationDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVerificationInstruction("This is the verification Instruction.");
                dialog.setRawMessage("This is the Raw Message");
                dialog.setMessageSpecification("This is the Message Specification");
                dialog.setVisible(true);
                System.out.println("Test Result Was "+dialog.isPassed());
                System.out.println("The skip checkbox was set to "+dialog.isSkipRemainingUserVerifications());
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    /** The Button panel. */
    private javax.swing.JPanel ButtonPanel;
    
    /** The Message panel. */
    private javax.swing.JPanel MessagePanel;
    
    /** The Verification context panel. */
    private javax.swing.JPanel VerificationContextPanel;
    
    /** The fail button. */
    private javax.swing.JButton failButton;
    
    /** The j label1. */
    private javax.swing.JLabel jLabel1;
    
    /** The j label2. */
    private javax.swing.JLabel jLabel2;
    
    /** The j panel1. */
    private javax.swing.JPanel jPanel1;
    
    /** The j scroll pane1. */
    private javax.swing.JScrollPane jScrollPane1;
    
    /** The message specification scroll pane. */
    private javax.swing.JScrollPane messageSpecificationScrollPane;
    
    /** The message specification text area. */
    public javax.swing.JTextArea messageSpecificationTextArea;
    
    /** The message tabbed pane. */
    private javax.swing.JTabbedPane messageTabbedPane;
    
    /** The pass button. */
    private javax.swing.JButton passButton;
    
    /** The raw message scroll pane. */
    private javax.swing.JScrollPane rawMessageScrollPane;
    
    /** The raw message text area. */
    public javax.swing.JTextArea rawMessageTextArea;
    
    /** The skip check box. */
    private javax.swing.JCheckBox skipCheckBox;
    
    /** The verification context text area. */
    public javax.swing.JTextArea verificationContextTextArea;
    // End of variables declaration//GEN-END:variables

}
