/*
 * AppLayerPanel.java - contains the AppLayerPanel Class source.
 *
 * Created on Mar 17, 2010, 5:26:20 PM
 */
package org.fhwa.c2cri.gui;

/**
 * The panel which allows the user to set Application Layer RTM and parameter settings.
 * This class provides a view of the panel.  Control of the panel is handled by a seperate
 * controlling (coordinator) class.
 *
 * @author TransCore ITS, LLC
 * Last Updated:  1/8/2014
 */
public class AppLayerPanel extends javax.swing.JPanel {

    /** 
     * Creates new JPanel AppLayerPanel by calling initComponents.
     */
    public AppLayerPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * define and initialize all elements of the panel.
     * WARNING: Do NOT manually modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        needsPanel = new javax.swing.JPanel();
        needsScrollPane = new javax.swing.JScrollPane();
        standardNeedsTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        needsClearjButton = new javax.swing.JButton();
        requirementsPanel = new javax.swing.JPanel();
        requirementsScrollPane = new javax.swing.JScrollPane();
        standardRequirementsTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        requirementsClearButton = new javax.swing.JButton();
        parametersPanel = new javax.swing.JPanel();
        parametersScrollPane = new javax.swing.JScrollPane();
        parametersTable = new javax.swing.JTable();

        needsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Select Need"));

        standardNeedsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1.0", "SOAP over HTTP", "O"},
                {"2.0", "XML over HTTP", "O"},
                {"3.0", "XML over FTP", "O"}
            },
            new String [] {
                "Need ID", "Description", "Project Requirements"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        standardNeedsTable.setToolTipText("The list of Application Layer Standard Needs.");
        standardNeedsTable.setFillsViewportHeight(true);
        standardNeedsTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        needsScrollPane.setViewportView(standardNeedsTable);
        standardNeedsTable.getAccessibleContext().setAccessibleName("Application Layer Needs Table");
        standardNeedsTable.getAccessibleContext().setAccessibleDescription("");

        jPanel3.setPreferredSize(new java.awt.Dimension(100, 23));

        needsClearjButton.setText("Clear Optional");
        needsClearjButton.setToolTipText("De-select all optional Needs");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(256, Short.MAX_VALUE)
                .addComponent(needsClearjButton)
                .addContainerGap(256, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(needsClearjButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout needsPanelLayout = new javax.swing.GroupLayout(needsPanel);
        needsPanel.setLayout(needsPanelLayout);
        needsPanelLayout.setHorizontalGroup(
            needsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, needsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(needsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
                    .addComponent(needsScrollPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE))
                .addContainerGap())
        );
        needsPanelLayout.setVerticalGroup(
            needsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, needsPanelLayout.createSequentialGroup()
                .addComponent(needsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        requirementsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Select Requirements"));

        standardRequirementsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1.0a", "WSDL Request-Response", "O",  new Boolean(true)},
                {"1.0b", "WSDL Subscription-Publication", "O",  new Boolean(true)},
                {"1.0c", "Message Encoding", "O",  new Boolean(true)},
                {"1.0d", "Message Transport", "O", null}
            },
            new String [] {
                "Requirement", "Description", "Project Requirements", "Selected"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        standardRequirementsTable.setToolTipText("The list of application layer requirements.");
        standardRequirementsTable.setFillsViewportHeight(true);
        standardRequirementsTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        requirementsScrollPane.setViewportView(standardRequirementsTable);
        standardRequirementsTable.getAccessibleContext().setAccessibleName("Application Layer Requirements Table");

        jPanel4.setPreferredSize(new java.awt.Dimension(100, 23));

        requirementsClearButton.setText("Clear Optional");
        requirementsClearButton.setToolTipText("De-select all requirements");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(256, Short.MAX_VALUE)
                .addComponent(requirementsClearButton)
                .addContainerGap(266, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(requirementsClearButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        requirementsClearButton.getAccessibleContext().setAccessibleDescription("De-select all optional requirements");

        javax.swing.GroupLayout requirementsPanelLayout = new javax.swing.GroupLayout(requirementsPanel);
        requirementsPanel.setLayout(requirementsPanelLayout);
        requirementsPanelLayout.setHorizontalGroup(
            requirementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, requirementsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(requirementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
                    .addComponent(requirementsScrollPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        requirementsPanelLayout.setVerticalGroup(
            requirementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(requirementsPanelLayout.createSequentialGroup()
                .addComponent(requirementsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        parametersPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Test Parameters"));

        parametersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Parameter", "Description", "Value"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        parametersTable.setToolTipText("Set application layer standard parameters.");
        parametersTable.setFillsViewportHeight(true);
        parametersTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        parametersScrollPane.setViewportView(parametersTable);
        parametersTable.getAccessibleContext().setAccessibleName("Application Layer Parameters Table");
        parametersTable.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout parametersPanelLayout = new javax.swing.GroupLayout(parametersPanel);
        parametersPanel.setLayout(parametersPanelLayout);
        parametersPanelLayout.setHorizontalGroup(
            parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, parametersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(parametersScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );
        parametersPanelLayout.setVerticalGroup(
            parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parametersPanelLayout.createSequentialGroup()
                .addComponent(parametersScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(needsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(requirementsPanel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(parametersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(needsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(requirementsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(parametersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    protected javax.swing.JButton needsClearjButton;
    private javax.swing.JPanel needsPanel;
    private javax.swing.JScrollPane needsScrollPane;
    private javax.swing.JPanel parametersPanel;
    protected javax.swing.JScrollPane parametersScrollPane;
    protected javax.swing.JTable parametersTable;
    protected javax.swing.JButton requirementsClearButton;
    private javax.swing.JPanel requirementsPanel;
    private javax.swing.JScrollPane requirementsScrollPane;
    protected javax.swing.JTable standardNeedsTable;
    protected javax.swing.JTable standardRequirementsTable;
    // End of variables declaration//GEN-END:variables
}
