/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.fhwa.c2cri.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author pearsonb
 */
public class EntityDataViewer extends javax.swing.JDialog {

    protected EntityDataViewer thisViewer;
    /**
     * Creates new form EntityDataViewer
     */
    public EntityDataViewer(boolean setOnTop) {
        initComponents();
        thisViewer = this;
        /** The OKButton.addActionListerner is used to accept and close the EntityDataViewer UI.*/
        OKButton.addActionListener(new ActionListener() 
        {
            public void actionPerformed(ActionEvent e) 
            {
                try
                {
                    thisViewer.dispose();
                    /** Closes the EntityDataViewer UI.*/
                }
                catch(Exception Ex)
                {
                    System.out.println("The error occured clicking the \"OK\" button in the \"Entity Data Viewer\" UI and the error is: \n" + Ex.getMessage());
                }
            }
        });
        this.setModalityType(ModalityType.APPLICATION_MODAL);
    }

    /**
     * Creates new form EntityDataViewer
     */
    public EntityDataViewer() {
        initComponents();
        thisViewer = this;
        /** The OKButton.addActionListerner is used to accept and close the EntityDataViewer UI.*/
        OKButton.addActionListener(new ActionListener() 
        {
            public void actionPerformed(ActionEvent e) 
            {
                try
                {
                    thisViewer.dispose();
                    /** Closes the EntityDataViewer UI.*/
                }
                catch(Exception Ex)
                {
                    System.out.println("The error occured clicking the \"OK\" button in the \"Entity Data Viewer\" UI and the error is: \n" + Ex.getMessage());
                }
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        EntityDataViewerTextArea = new javax.swing.JTextArea();
        OKButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(421, 302));

        EntityDataViewerTextArea.setColumns(20);
        EntityDataViewerTextArea.setRows(5);
        EntityDataViewerTextArea.setToolTipText("Entity Data Viewer Text Area");
        EntityDataViewerTextArea.setName("EntityDataViewerTextArea"); // NOI18N
        jScrollPane1.setViewportView(EntityDataViewerTextArea);
        EntityDataViewerTextArea.getAccessibleContext().setAccessibleName("EntityDataViewerTextArea");

        OKButton.setText("OK");
        OKButton.setToolTipText("Entity Data Viewer OK Button");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(OKButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(OKButton)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EntityDataViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EntityDataViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EntityDataViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EntityDataViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EntityDataViewer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextArea EntityDataViewerTextArea;
    public javax.swing.JButton OKButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
