/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * HelpUI.java
 *
 * Created on Mar 26, 2010, 5:06:08 PM
 */

package org.fhwa.c2cri.gui;

/**
 * The Help about dialog box.
 *
 * @author TransCore ITS, LLC
 * Last Updated:  1/8/2014
 */
public class HelpUI extends javax.swing.JDialog {


    /**
     * Creates new form HelpUI.
     *
     * @param parent the parent frame for this object
     * @param modal indicates whether the dialog should be modal
     */
    public HelpUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        contactInfoLabel = new javax.swing.JLabel();
        riVersionLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About the C2C RI");
        setMinimumSize(new java.awt.Dimension(400, 300));

        okButton.setText("OK");
        okButton.setToolTipText("Close the Help Window");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        contactInfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contactInfoLabel.setText("Refer to the C2C RI User's Manual for help and contact information.");

        riVersionLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        riVersionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        riVersionLabel.setText(" C2C RI Version 1.0");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/fhwa/c2cri/gui/US-Department-of-Transportation (120x120).jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(riVersionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactInfoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(okButton))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(riVersionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(contactInfoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(okButton)
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Ok button action performed.
     * 
     * Pre-Conditions: N/A
     * Post-Conditions: N/A
     *
     * @param evt the evt
     */
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_okButtonActionPerformed

    /**
     * The main method.
     * 
     * Pre-Conditions: N/A
     * Post-Conditions: N/A
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HelpUI dialog = new HelpUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    /**
     * Makes the HelpUI dialog visible to the operator.
     */
    public void showDialog(){
    setVisible(true);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contactInfoLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton okButton;
    public javax.swing.JLabel riVersionLabel;
    // End of variables declaration//GEN-END:variables

}
