
/*
 * TestExecutionPanel.java - Contains the TestExecutionPanel Class which provides the user with
 * an interface to run a test.
 *
 * Created on Feb 12, 2010, 7:45:33 PM
 */
package org.fhwa.c2cri.gui;

import java.awt.event.KeyEvent;

/**
 * This class represents the TestExecutionPanel which the user controls the test with.
 *
 * @author TransCore ITS, LLC
 * Last Updated:  1/8/2014
 */
public class TestExecutionPanel extends javax.swing.JPanel {

    /**
     * Creates new form TestExecutionPanel.  All panel components are initialized by
     * calling initComponents.
     */
    public TestExecutionPanel() {
        initComponents();
        this.jRunningLabel.setVisible(false);
        this.resumeButton.setEnabled(false);
        this.pauseButton.setEnabled(false);
        this.terminateButton.setEnabled(false);
        this.runButton.setEnabled(false);
        this.runButton.setMnemonic(KeyEvent.VK_R);
        this.pauseButton.setMnemonic(KeyEvent.VK_P);
        this.resumeButton.setMnemonic(KeyEvent.VK_S);
        this.terminateButton.setMnemonic(KeyEvent.VK_C);

    }

    /** This method is called from within the constructor to
     * initialize the panel.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        testNameLabel = new javax.swing.JLabel();
        testNameTextField = new javax.swing.JTextField();
        runButton = new javax.swing.JButton();
        pauseButton = new javax.swing.JButton();
        resumeButton = new javax.swing.JButton();
        terminateButton = new javax.swing.JButton();
        reportPanel = new javax.swing.JPanel();
        statusTabbedPane = new javax.swing.JTabbedPane();
        testResultsPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        testCaseTable = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        testResultsTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTestCaseDescription = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        testStatusPanel = new javax.swing.JPanel();
        statusTextScrollPane = new javax.swing.JScrollPane();
        statusTextTable = new javax.swing.JTable();
        testStatusLabel = new javax.swing.JLabel();
        actionTextScrollPane = new javax.swing.JScrollPane();
        actionTextTable = new javax.swing.JTable();
        testScriptLogLabel = new javax.swing.JLabel();
        jTestExecutionProgressBar = new javax.swing.JProgressBar();
        jRunningLabel = new javax.swing.JLabel();
        jTabbedPaneTestCases = new javax.swing.JTabbedPane();
        jScrollPaneInfoLayer = new javax.swing.JScrollPane();
        infoStandardTree = new javax.swing.JTree();
        jScrollPaneAppLayer = new javax.swing.JScrollPane();
        appStandardTree = new javax.swing.JTree();

        setDoubleBuffered(false);
        setMaximumSize(new java.awt.Dimension(750, 550));
        setMinimumSize(new java.awt.Dimension(750, 550));
        setPreferredSize(new java.awt.Dimension(750, 550));

        jSplitPane1.setDividerLocation(135);

        jPanel1.setMinimumSize(new java.awt.Dimension(600, 525));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 550));

        testNameLabel.setText("Test Name");

        testNameTextField.setToolTipText("The user provided test name.");
        testNameTextField.setEnabled(false);

        runButton.setText("Run");
        runButton.setToolTipText("Run the test.");

        pauseButton.setText("Pause");
        pauseButton.setToolTipText("Pause the currently running test.");
        pauseButton.setEnabled(false);

        resumeButton.setText("Resume");
        resumeButton.setToolTipText("Resume running the test.");
        resumeButton.setEnabled(false);

        terminateButton.setText("Close");
        terminateButton.setToolTipText("Stop testing and exit.");

        reportPanel.setMinimumSize(new java.awt.Dimension(569, 432));

        statusTabbedPane.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        statusTabbedPane.setToolTipText("");

        testResultsPanel.setToolTipText("");

        testCaseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        testCaseTable.setToolTipText("The results of test cases executed.");
        jScrollPane3.setViewportView(testCaseTable);
        testCaseTable.getAccessibleContext().setAccessibleName("Test Case Table");

        testResultsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        testResultsTable.setToolTipText("The results of test steps executed during a selected test case.");
        jScrollPane4.setViewportView(testResultsTable);
        testResultsTable.getAccessibleContext().setAccessibleName("Test Step Results Table");

        jLabel1.setText("Test Case Results");

        jLabel2.setText("Test Step Results");

        jTestCaseDescription.setEditable(false);
        jTestCaseDescription.setColumns(20);
        jTestCaseDescription.setLineWrap(true);
        jTestCaseDescription.setRows(2);
        jTestCaseDescription.setToolTipText("Selected Test Case Description");
        jTestCaseDescription.setWrapStyleWord(true);
        jScrollPane5.setViewportView(jTestCaseDescription);

        jLabel3.setText("Test Case Description");

        javax.swing.GroupLayout testResultsPanelLayout = new javax.swing.GroupLayout(testResultsPanel);
        testResultsPanel.setLayout(testResultsPanelLayout);
        testResultsPanelLayout.setHorizontalGroup(
            testResultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, testResultsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(testResultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, testResultsPanelLayout.createSequentialGroup()
                        .addGroup(testResultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        testResultsPanelLayout.setVerticalGroup(
            testResultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(testResultsPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                .addContainerGap())
        );

        statusTabbedPane.addTab("Test Results", null, testResultsPanel, "Test Results Tab");
        testResultsPanel.getAccessibleContext().setAccessibleName("Test Results Summary");
        testResultsPanel.getAccessibleContext().setAccessibleDescription("Displays the summary results of the test cases and steps executed.");

        testStatusPanel.setPreferredSize(new java.awt.Dimension(600, 550));

        statusTextTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        statusTextScrollPane.setViewportView(statusTextTable);

        testStatusLabel.setText("Test Status");

        actionTextTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        actionTextScrollPane.setViewportView(actionTextTable);

        testScriptLogLabel.setText("Test Script Log");

        javax.swing.GroupLayout testStatusPanelLayout = new javax.swing.GroupLayout(testStatusPanel);
        testStatusPanel.setLayout(testStatusPanelLayout);
        testStatusPanelLayout.setHorizontalGroup(
            testStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(testStatusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(testStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statusTextScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
                    .addComponent(testStatusLabel)
                    .addComponent(testScriptLogLabel)
                    .addComponent(actionTextScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE))
                .addContainerGap())
        );
        testStatusPanelLayout.setVerticalGroup(
            testStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(testStatusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(testStatusLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(statusTextScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(testScriptLogLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(actionTextScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );

        statusTabbedPane.addTab("Test Log", null, testStatusPanel, "Provides details of test script actions.");
        testStatusPanel.getAccessibleContext().setAccessibleName("Test Script Log Tab");
        testStatusPanel.getAccessibleContext().setAccessibleDescription("Provides details of test script actions.");

        javax.swing.GroupLayout reportPanelLayout = new javax.swing.GroupLayout(reportPanel);
        reportPanel.setLayout(reportPanelLayout);
        reportPanelLayout.setHorizontalGroup(
            reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        reportPanelLayout.setVerticalGroup(
            reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportPanelLayout.createSequentialGroup()
                .addComponent(statusTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                .addContainerGap())
        );

        jRunningLabel.setText("Running...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(reportPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(testNameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(testNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(runButton)
                        .addGap(39, 39, 39)
                        .addComponent(pauseButton)
                        .addGap(29, 29, 29)
                        .addComponent(resumeButton)
                        .addGap(27, 27, 27)
                        .addComponent(terminateButton)
                        .addGap(37, 37, 37)
                        .addComponent(jRunningLabel)
                        .addGap(18, 18, 18)
                        .addComponent(jTestExecutionProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(terminateButton)
                        .addComponent(resumeButton)
                        .addComponent(pauseButton)
                        .addComponent(runButton))
                    .addComponent(jTestExecutionProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRunningLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(testNameLabel)
                    .addComponent(testNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reportPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        testNameTextField.getAccessibleContext().setAccessibleName("Test Name");
        testNameTextField.getAccessibleContext().setAccessibleDescription("The primary name given to this test.");

        jSplitPane1.setRightComponent(jPanel1);

        jTabbedPaneTestCases.setToolTipText("Information Layer and Application Layer Standard Test Cases");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("C2CRI");
        infoStandardTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        infoStandardTree.setToolTipText("Information Layer Test Cases");
        jScrollPaneInfoLayer.setViewportView(infoStandardTree);
        infoStandardTree.getAccessibleContext().setAccessibleName("Information Layer Test Case Tree");
        infoStandardTree.getAccessibleContext().setAccessibleDescription("Informaiton Layer Test Cases");

        jTabbedPaneTestCases.addTab("Information", null, jScrollPaneInfoLayer, "Information Layer Standard Test Cases");
        jScrollPaneInfoLayer.getAccessibleContext().setAccessibleName("Information Layer Standard Tab");
        jScrollPaneInfoLayer.getAccessibleContext().setAccessibleDescription("Information Layer Standard Test Cases");

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("C2CRI");
        appStandardTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        appStandardTree.setToolTipText("Application Layer Standard Test Cases");
        jScrollPaneAppLayer.setViewportView(appStandardTree);
        appStandardTree.getAccessibleContext().setAccessibleName("Application Layer Test Cases");

        jTabbedPaneTestCases.addTab("Application", null, jScrollPaneAppLayer, "Application Layer Standard Test Cases");
        jScrollPaneAppLayer.getAccessibleContext().setAccessibleName("Application Layer Standard Test Case Tree");
        jScrollPaneAppLayer.getAccessibleContext().setAccessibleDescription("Application Layer Standard Test Cases");

        jSplitPane1.setLeftComponent(jTabbedPaneTestCases);
        jTabbedPaneTestCases.getAccessibleContext().setAccessibleName("Information and Application Layer Test Cases");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane actionTextScrollPane;
    protected javax.swing.JTable actionTextTable;
    protected javax.swing.JTree appStandardTree;
    protected javax.swing.JTree infoStandardTree;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    protected javax.swing.JLabel jRunningLabel;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    protected javax.swing.JScrollPane jScrollPaneAppLayer;
    protected javax.swing.JScrollPane jScrollPaneInfoLayer;
    private javax.swing.JSplitPane jSplitPane1;
    protected javax.swing.JTabbedPane jTabbedPaneTestCases;
    protected javax.swing.JTextArea jTestCaseDescription;
    protected javax.swing.JProgressBar jTestExecutionProgressBar;
    protected javax.swing.JButton pauseButton;
    protected javax.swing.JPanel reportPanel;
    protected javax.swing.JButton resumeButton;
    protected javax.swing.JButton runButton;
    protected javax.swing.JTabbedPane statusTabbedPane;
    private javax.swing.JScrollPane statusTextScrollPane;
    protected javax.swing.JTable statusTextTable;
    protected javax.swing.JButton terminateButton;
    protected javax.swing.JTable testCaseTable;
    private javax.swing.JLabel testNameLabel;
    protected javax.swing.JTextField testNameTextField;
    protected javax.swing.JPanel testResultsPanel;
    protected javax.swing.JTable testResultsTable;
    private javax.swing.JLabel testScriptLogLabel;
    private javax.swing.JLabel testStatusLabel;
    protected javax.swing.JPanel testStatusPanel;
    // End of variables declaration//GEN-END:variables
}
