/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.fhwa.c2cri.gui.testmodel.testcasedata.editor;

import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author TransCore ITS, LLC
 */
public class AddParameterPanel extends javax.swing.JPanel {

    final JList list = new JList(new DefaultListModel());

    /**
     * Creates new form AddParameterPanel
     */
    public AddParameterPanel() {
        initComponents();

     
    }

    public void setSymbolPanelEnabled(boolean b) {
        jSymbolPanel.setVisible(b);
    }

    public void setStringPanelEnabled(boolean b) {
        jStringPanel.setVisible(b);
    }

    public String getParameterName() {
        return jNameTextField.getText();
    }

    public String getParameterDescription() {
        return jDescriptionTextArea.getText().replace("\n", "").replace("\r", "");
    }

    public String getParameterType() {
        return String.valueOf(jComboBox1.getSelectedItem());
    }

    public String[] getParameterTypeValues() {
        int symbolValueCount = list.getModel().getSize();
        String[] symbolValues = new String[symbolValueCount];
        if (symbolValueCount > 0) {
            for (int ii = 0; ii < symbolValueCount; ii++) {
                symbolValues[ii] = (String) list.getModel().getElementAt(ii);
            }
        }
        return symbolValues;
    }

    public String getParameterValue() {
        return jValueTextArea.getText().replace("\n","").replace("\r","");
    }

    public int getParameterMinLength() {
        int minLength = 0;
        if (jMinLengthCheckBox.isSelected()){
            try{
            minLength = Integer.parseInt(jMinLengthTextField.getText());
            } catch (Exception ex){
                
            }
        }
        return minLength;
    }

    public int getParameterMaxLength() {
        int maxLength = 1;
        if (jMaxLengthCheckBox.isSelected()){
            try{
            maxLength = Integer.parseInt(jMaxLengthTextField.getText());
            } catch (Exception ex){
                
            }
        }
        return maxLength;
    }

    public boolean isValidParameterLength(){
        if (jMaxLengthCheckBox.isSelected() && jMinLengthCheckBox.isSelected()){
            if (getParameterMaxLength() < getParameterMinLength()){
                return false;
            } else return true;
        }
        return true;        
    }
    
    public boolean isParameterMinLengthSelected(){
        return jMinLengthCheckBox.isSelected();
    }

    public boolean isParameterMaxLengthSelected(){
        return jMaxLengthCheckBox.isSelected();
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSymbolPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSymbolComboBox = new javax.swing.JComboBox<>();
        jSymbolAddButton = new javax.swing.JButton();
        jSymbolRemoveButton = new javax.swing.JButton();
        jStringPanel = new javax.swing.JPanel();
        jMinLengthCheckBox = new javax.swing.JCheckBox();
        jMaxLengthCheckBox = new javax.swing.JCheckBox();
        jMinLengthTextField = new javax.swing.JTextField();
        jMaxLengthTextField = new javax.swing.JTextField();
        jValuePanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jValueTextArea = new javax.swing.JTextArea();
        jMainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jNameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jDescriptionTextArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        jLabel4.setText("Symbol Values");

        jSymbolComboBox.setEditable(true);
        jSymbolComboBox.setMinimumSize(new java.awt.Dimension(63, 20));
        jSymbolComboBox.setPreferredSize(new java.awt.Dimension(63, 20));

        jSymbolAddButton.setText("Add");
        jSymbolAddButton.setToolTipText("Add a new symbol to the list");
        jSymbolAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSymbolAddButtonActionPerformed(evt);
            }
        });

        jSymbolRemoveButton.setText("Remove");
        jSymbolRemoveButton.setToolTipText("Remove an existing symbol from the list");
        jSymbolRemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSymbolRemoveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jSymbolPanelLayout = new javax.swing.GroupLayout(jSymbolPanel);
        jSymbolPanel.setLayout(jSymbolPanelLayout);
        jSymbolPanelLayout.setHorizontalGroup(
            jSymbolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jSymbolPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jSymbolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jSymbolPanelLayout.createSequentialGroup()
                        .addComponent(jSymbolAddButton)
                        .addGap(22, 22, 22)
                        .addComponent(jSymbolRemoveButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSymbolComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jSymbolPanelLayout.setVerticalGroup(
            jSymbolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jSymbolPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jSymbolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jSymbolComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jSymbolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSymbolAddButton)
                    .addComponent(jSymbolRemoveButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMinLengthCheckBox.setText("Minimum Length");
        jMinLengthCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMinLengthCheckBoxActionPerformed(evt);
            }
        });

        jMaxLengthCheckBox.setText("Maximum Length");
        jMaxLengthCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMaxLengthCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jStringPanelLayout = new javax.swing.GroupLayout(jStringPanel);
        jStringPanel.setLayout(jStringPanelLayout);
        jStringPanelLayout.setHorizontalGroup(
            jStringPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jStringPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jStringPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jStringPanelLayout.createSequentialGroup()
                        .addComponent(jMinLengthCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jMinLengthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jStringPanelLayout.createSequentialGroup()
                        .addComponent(jMaxLengthCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jMaxLengthTextField)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jStringPanelLayout.setVerticalGroup(
            jStringPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jStringPanelLayout.createSequentialGroup()
                .addGroup(jStringPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMinLengthCheckBox)
                    .addComponent(jMinLengthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jStringPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMaxLengthCheckBox)
                    .addComponent(jMaxLengthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jLabel5.setText("Value");

        jValueTextArea.setColumns(20);
        jValueTextArea.setRows(5);
        jScrollPane2.setViewportView(jValueTextArea);

        javax.swing.GroupLayout jValuePanelLayout = new javax.swing.GroupLayout(jValuePanel);
        jValuePanel.setLayout(jValuePanelLayout);
        jValuePanelLayout.setHorizontalGroup(
            jValuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jValuePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jValuePanelLayout.setVerticalGroup(
            jValuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jValuePanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );

        jLabel1.setText("Name");

        jLabel2.setText("Description");

        jDescriptionTextArea.setColumns(20);
        jDescriptionTextArea.setRows(5);
        jScrollPane1.setViewportView(jDescriptionTextArea);

        jLabel3.setText("Type");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "String", "Boolean", "Symbol", "File" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jMainPanelLayout = new javax.swing.GroupLayout(jMainPanel);
        jMainPanel.setLayout(jMainPanelLayout);
        jMainPanelLayout.setHorizontalGroup(
            jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jMainPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jNameTextField))
                    .addGroup(jMainPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(jMainPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jMainPanelLayout.setVerticalGroup(
            jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jValuePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jStringPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSymbolPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSymbolPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jStringPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jValuePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String selection = String.valueOf(jComboBox1.getSelectedItem());
        if (selection.equals("String")) {
            setStringPanelEnabled(true);
            setSymbolPanelEnabled(false);
            if (jMinLengthCheckBox.isSelected()) {
                jMinLengthTextField.setEnabled(true);
            } else {
                jMinLengthTextField.setEnabled(false);
            }

            if (jMaxLengthCheckBox.isSelected()) {
                jMaxLengthTextField.setEnabled(true);
            } else {
                jMaxLengthTextField.setEnabled(false);
            }

        } else if (selection.equals("Symbol")) {
            setStringPanelEnabled(false);
            setSymbolPanelEnabled(true);
        } else {
            setStringPanelEnabled(false);
            setSymbolPanelEnabled(false);
        }
        this.revalidate();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jMinLengthCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMinLengthCheckBoxActionPerformed
        if (jMinLengthCheckBox.isSelected()) {
            jMinLengthTextField.setEnabled(true);
        } else
            jMinLengthTextField.setEnabled(false);
    }//GEN-LAST:event_jMinLengthCheckBoxActionPerformed

    private void jMaxLengthCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMaxLengthCheckBoxActionPerformed
        if (jMaxLengthCheckBox.isSelected()) {
            jMaxLengthTextField.setEnabled(true);
        } else
            jMaxLengthTextField.setEnabled(false);
    }//GEN-LAST:event_jMaxLengthCheckBoxActionPerformed

    private void jSymbolAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSymbolAddButtonActionPerformed
        if (jSymbolComboBox.getSelectedItem() != null){            
            ((DefaultListModel) list.getModel()).addElement(jSymbolComboBox.getSelectedItem());
            jSymbolComboBox.insertItemAt((String) jSymbolComboBox.getSelectedItem(), 0);        
        }
    }//GEN-LAST:event_jSymbolAddButtonActionPerformed

    private void jSymbolRemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSymbolRemoveButtonActionPerformed
        if (jSymbolComboBox.getSelectedItem() != null) {           
            ((DefaultListModel) list.getModel()).removeElement(jSymbolComboBox.getSelectedItem());
            jSymbolComboBox.removeItem((String) jSymbolComboBox.getSelectedItem());       
        }
    }//GEN-LAST:event_jSymbolRemoveButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JTextArea jDescriptionTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jMainPanel;
    private javax.swing.JCheckBox jMaxLengthCheckBox;
    private javax.swing.JTextField jMaxLengthTextField;
    private javax.swing.JCheckBox jMinLengthCheckBox;
    private javax.swing.JTextField jMinLengthTextField;
    private javax.swing.JTextField jNameTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jStringPanel;
    private javax.swing.JButton jSymbolAddButton;
    private javax.swing.JComboBox<String> jSymbolComboBox;
    private javax.swing.JPanel jSymbolPanel;
    private javax.swing.JButton jSymbolRemoveButton;
    private javax.swing.JPanel jValuePanel;
    private javax.swing.JTextArea jValueTextArea;
    // End of variables declaration//GEN-END:variables
}
