//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.09 at 09:05:15 AM EST 
//


package org.fhwa.c2cri.ntcip2306v109.c2cadmin;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for C2cMessageSubscription complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="C2cMessageSubscription">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="informationalText" type="{http://www.ntcip.org/c2c-message-administration}InformationalText" minOccurs="0"/>
 *         &lt;element name="returnAddress" type="{http://www.ntcip.org/c2c-message-administration}ReturnAddress"/>
 *         &lt;element name="subscriptionAction" type="{http://www.ntcip.org/c2c-message-administration}SubscriptionAction"/>
 *         &lt;element name="subscriptionType" type="{http://www.ntcip.org/c2c-message-administration}SubscriptionType"/>
 *         &lt;element name="subscriptionID" type="{http://www.ntcip.org/c2c-message-administration}SubscriptionID"/>
 *         &lt;element name="subscriptionName" type="{http://www.ntcip.org/c2c-message-administration}SubscriptionName" minOccurs="0"/>
 *         &lt;element name="subscriptionTimeFrame" type="{http://www.ntcip.org/c2c-message-administration}SubscriptionTimeFrame" minOccurs="0"/>
 *         &lt;element name="subscriptionFrequency" type="{http://www.ntcip.org/c2c-message-administration}SubscriptionFrequency"/>
 *         &lt;element name="broadcastAlerts" type="{http://www.ntcip.org/c2c-message-administration}BroadcastAlerts" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "C2cMessageSubscription", propOrder = {
    "informationalText",
    "returnAddress",
    "subscriptionAction",
    "subscriptionType",
    "subscriptionID",
    "subscriptionName",
    "subscriptionTimeFrame",
    "subscriptionFrequency",
    "broadcastAlerts"
})
@XmlRootElement(name = "c2cMessageSubscription")
public class C2CMessageSubscription {

    protected String informationalText;
    @XmlElement(required = true)
    protected String returnAddress;
    @XmlElement(required = true)
    protected SubscriptionAction subscriptionAction;
    @XmlElement(required = true)
    protected SubscriptionType subscriptionType;
    @XmlElement(required = true)
    protected String subscriptionID;
    protected String subscriptionName;
    protected SubscriptionTimeFrame subscriptionTimeFrame;
    protected long subscriptionFrequency;
    protected BroadcastAlerts broadcastAlerts;

    /**
     * Gets the value of the informationalText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInformationalText() {
        return informationalText;
    }

    /**
     * Sets the value of the informationalText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInformationalText(String value) {
        this.informationalText = value;
    }

    /**
     * Gets the value of the returnAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReturnAddress() {
        return returnAddress;
    }

    /**
     * Sets the value of the returnAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReturnAddress(String value) {
        this.returnAddress = value;
    }

    /**
     * Gets the value of the subscriptionAction property.
     * 
     * @return
     *     possible object is
     *     {@link SubscriptionAction }
     *     
     */
    public SubscriptionAction getSubscriptionAction() {
        return subscriptionAction;
    }

    /**
     * Sets the value of the subscriptionAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubscriptionAction }
     *     
     */
    public void setSubscriptionAction(SubscriptionAction value) {
        this.subscriptionAction = value;
    }

    /**
     * Gets the value of the subscriptionType property.
     * 
     * @return
     *     possible object is
     *     {@link SubscriptionType }
     *     
     */
    public SubscriptionType getSubscriptionType() {
        return subscriptionType;
    }

    /**
     * Sets the value of the subscriptionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubscriptionType }
     *     
     */
    public void setSubscriptionType(SubscriptionType value) {
        this.subscriptionType = value;
    }

    /**
     * Gets the value of the subscriptionID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubscriptionID() {
        return subscriptionID;
    }

    /**
     * Sets the value of the subscriptionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubscriptionID(String value) {
        this.subscriptionID = value;
    }

    /**
     * Gets the value of the subscriptionName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubscriptionName() {
        return subscriptionName;
    }

    /**
     * Sets the value of the subscriptionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubscriptionName(String value) {
        this.subscriptionName = value;
    }

    /**
     * Gets the value of the subscriptionTimeFrame property.
     * 
     * @return
     *     possible object is
     *     {@link SubscriptionTimeFrame }
     *     
     */
    public SubscriptionTimeFrame getSubscriptionTimeFrame() {
        return subscriptionTimeFrame;
    }

    /**
     * Sets the value of the subscriptionTimeFrame property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubscriptionTimeFrame }
     *     
     */
    public void setSubscriptionTimeFrame(SubscriptionTimeFrame value) {
        this.subscriptionTimeFrame = value;
    }

    /**
     * Gets the value of the subscriptionFrequency property.
     * 
     */
    public long getSubscriptionFrequency() {
        return subscriptionFrequency;
    }

    /**
     * Sets the value of the subscriptionFrequency property.
     * 
     */
    public void setSubscriptionFrequency(long value) {
        this.subscriptionFrequency = value;
    }

    /**
     * Gets the value of the broadcastAlerts property.
     * 
     * @return
     *     possible object is
     *     {@link BroadcastAlerts }
     *     
     */
    public BroadcastAlerts getBroadcastAlerts() {
        return broadcastAlerts;
    }

    /**
     * Sets the value of the broadcastAlerts property.
     * 
     * @param value
     *     allowed object is
     *     {@link BroadcastAlerts }
     *     
     */
    public void setBroadcastAlerts(BroadcastAlerts value) {
        this.broadcastAlerts = value;
    }

}
