//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.09 at 09:05:15 AM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ntcip.org/c2c-message-administration")
package org.fhwa.c2cri.ntcip2306v109.c2cadmin;
