/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TempFrameForTest.java
 *
 * Created on Jul 18, 2011, 4:27:49 PM
 */
package test.progresstest;

import org.fhwa.c2cri.gui.ProgressUI;

/**
 * The Class TempFrameForTest.
 *
 * @author TransCore ITS, LLC
 * Last Updated:  1/8/2014
 */
public class TempFrameForTest extends javax.swing.JFrame {

    /** The wait one time. */
    private Integer waitOneTime = 2500;

    /**
     * Creates new form TempFrameForTest.
     */
    public TempFrameForTest() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Wait 2.5s");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Wait 5s");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Wait ??");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addGap(58, 58, 58)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(170, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * J button1 action performed.
     * 
     * Pre-Conditions: N/A
     * Post-Conditions: N/A
     *
     * @param evt the evt
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        ProgressUI thisProgress = new ProgressUI(this, true, "Button Action 1");
        BasicGUIActionWrapper button1Action = new BasicGUIActionWrapper(this, "Button Action 1") {

            @Override
            protected Boolean actionMethod() throws Exception {
                Thread.sleep(waitOneTime);
                return true;
            }
        };
        button1Action.execute();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * J button2 action performed.
     * 
     * Pre-Conditions: N/A
     * Post-Conditions: N/A
     *
     * @param evt the evt
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        final Integer waitTime = 5000;
        final javax.swing.JFrame thisFrame = this;

//        ProgressUI thisProgress = new ProgressUI(this, true, "Button Action 2");
        BasicGUIActionWrapper button2Action = new BasicGUIActionWrapper(this, "Button Action 2") {

            @Override
            protected Boolean actionMethod() throws Exception {
                Thread.sleep(waitTime);
                return true;
            }

            @Override
            protected void wrapUp(Boolean result) {
                if (!result) {
                    javax.swing.JOptionPane.showMessageDialog(thisFrame, "An error was encountered trying to complete the action.");
                } else {
                    javax.swing.JOptionPane.showMessageDialog(thisFrame, "Successfully Completed the action.");

                }
            }
        };
        button2Action.execute();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * J button3 action performed.
     * 
     * Pre-Conditions: N/A
     * Post-Conditions: N/A
     *
     * @param evt the evt
     */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        final Integer waitTime = 5000;

        ReturnObjectGUIActionWrapper button3Action = new ReturnObjectGUIActionWrapper(this, "Button Action 3") {

            @Override
            protected Boolean actionMethod() throws Exception {
                Thread.sleep(waitTime);
                return false;
            }
        };
        button3Action.execute();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * The main method.
     * 
     * Pre-Conditions: N/A
     * Post-Conditions: N/A
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TempFrameForTest().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    /** The j button1. */
    private javax.swing.JButton jButton1;
    
    /** The j button2. */
    private javax.swing.JButton jButton2;
    
    /** The j button3. */
    private javax.swing.JButton jButton3;
    // End of variables declaration//GEN-END:variables
}
