name: SonarQube Analysis

on:
  push:
    branches:
      - feature/sonar_cloud

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'temurin'
    - name: Download SonarScanner
      run: |
        $url = "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-windows.zip"
        $outputFile = "sonarscanner.zip"
        Invoke-WebRequest -Uri $url -OutFile $outputFile
        Expand-Archive $outputFile -DestinationPath C:\sonarscanner
        Remove-Item $outputFile
        $env:PATH += ";C:\sonarscanner\bin"
      shell: powershell
    - name: List Repository Contents
      run: |
        ls $GITHUB_WORKSPACE
        pwd
        cd $GITHUB_WORKSPACE/C2CRIBuildDir/buildfiles
        buildRIcode
      shell: bash
    - name: SonarQube Analysis
      run: |
        sonar-scanner -D"sonar.projectKey=RIGUI" -D"sonar.sources=$GITHUB_WORKSPACE\C2CRIBuildDir\projects\C2C-RI\src\RIGUI\src" -D"sonar.java.binaries=$GITHUB_WORKSPACE\C2CRIBuildDir\projects\C2C-RI\src\RIGUI\build\classes" -D"sonar.organization=usdot-fhwa-stol" -D"sonar.host.url=https://sonarcloud.io" -D"sonar.projectBaseDir=$GITHUB_WORKSPACE\C2CRIBuildDir\projects\C2C-RI\src\RIGUI"
      shell: powershell
