name: SonarQube Analysis

on:
  push:
    branches:
      - feature/sonar_cloud

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'temurin'
    - name: Download SonarScanner
      run: |
        $url = "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-windows.zip"
        $outputFile = "sonarscanner.zip"
        Invoke-WebRequest -Uri $url -OutFile $outputFile
        Expand-Archive $outputFile -DestinationPath C:\sonarscanner
        Remove-Item $outputFile
        $env:PATH += ";C:\sonarscanner\bin"
      shell: powershell
    - name: Find Sonar Scanner Path
      id: find-sonar-scanner
      run: |
        $sonarScannerPath = Get-Command sonar-scanner.bat | Select-Object -ExpandProperty Source
        echo "::set-output name=sonar_scanner_path::$sonarScannerPath"
      shell: powershell
          
    - name: Build C2CRI
      run: |
        cd \a\c2c-ri\c2c-ri\C2CRIBuildDir\buildfiles
        dir
        Start-Process -Wait -FilePath .\buildRICode.bat
      shell: powershell

    - name: SonarQube Analysis
      run: |
        cd C:\sonarscanner\bin
        dir
        sonar-scanner -D"sonar.projectKey=usdot-fhwa-stol_c2cri-rigui" -D"sonar.sources=\a\c2c-ri\c2c-ri\C2CRIBuildDir\projects\C2C-RI\src\RIGUI\src" -D"sonar.java.binaries=\a\c2c-ri\c2c-ri\C2CRIBuildDir\projects\C2C-RI\src\RIGUI\build\classes" -D"sonar.organization=usdot-fhwa-stol" -D"sonar.host.url=https://sonarcloud.io" -D"sonar.projectBaseDir=\a\c2c-ri\c2c-ri\C2CRIBuildDir\projects\C2C-RI\src\RIGUI"
      shell: powershell
