name: SonarQube Analysis

on:
  push:
    branches:
      - feature/sonar_cloud

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'temurin'


    - name: Download SonarScanner
      run: |
        $url = "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-windows.zip"
        $outputFile = "sonarscanner.zip"
        Invoke-WebRequest -Uri $url -OutFile $outputFile
        Expand-Archive $outputFile -DestinationPath C:\sonarscanner
        Remove-Item $outputFile
        $env:PATH += ";C:\sonarscanner\bin"
      shell: powershell
    - name: Install SonarQube Scanner for MSBuild (if needed)
      run: |
        # If your project requires the SonarScanner for MSBuild, download and install it here.
        # You can find the download link on the SonarQube website.
      shell: powershell

    - name: Download and Install SonarQube
      run: |
        $url = "https://downloads.sonarqube.org/sonarqube-9.6.0.41062.zip"
        $outputFile = "sonarqube.zip"
        Invoke-WebRequest -Uri $url -OutFile $outputFile
        Expand-Archive -Path $outputFile -DestinationPath C:\sonarqube
        Remove-Item $outputFile
        $env:PATH += ";C:\sonarqube\bin\windows-x86-64"
      shell: powershell

    - name: Build C2CRI
      run: |
        cd $GITHUB_WORKSPACE/C2CRIBuildDir/buildfiles/
        buildRIcode.bat
        build.bat

    - name: SonarQube Analysis
      run: |
        sonar-scanner -D"sonar.projectKey=RIGUI" -D"sonar.sources=$GITHUB_WORKSPACE\C2CRIBuildDir\projects\C2C-RI\src\RIGUI\src" -D"sonar.java.binaries=$GITHUB_WORKSPACE\C2CRIBuildDir\projects\C2C-RI\src\RIGUI\build\classes" -D"sonar.organization=usdot-fhwa-stol" -D"sonar.host.url=https://sonarcloud.io" -D"sonar.projectBaseDir=$GITHUB_WORKSPACE\C2CRIBuildDir\projects\C2C-RI\src\RIGUI"
      shell: powershell
